- name: Add LizardFS Repository Key
  apt_key:
    url: http://packages.lizardfs.com/lizardfs.key
    keyring: /etc/apt/trusted.gpg.d/lizardfs.gpg
    state: present
  when: ansible_pkg_mgr == "apt"

- name: Add LizardFS Repository to sources.list
  apt_repository:
    repo: 'deb http://packages.lizardfs.com/{{ ansible_distribution|lower }}/{{ ansible_lsb.codename }} {{ ansible_lsb.codename }} main'
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == "apt"

- name: Add LizardFS CentOS Repository
  get_url:
      url: http://packages.lizardfs.com/yum/centos7/lizardfs.repo
      dest: /etc/yum.repos.d/lizardfs.repo
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int == 7

